# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# (Kotlin-specific) To enable caching of project dependencies.
org.gradle.parallel=true

# Fabric
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.17.3
fabric_version=0.128.2+1.21.5

# Mod Properties
mod_version=1.0.0
maven_group=com.boxedironfarm
archives_base_name=boxed-iron-farm
